### ISSUE TITLE
bam_alignment_qc to crash with the Keyerror message

### ISSUE THREAD

**Issue by lynn12345621** [nanoporetech/wub#8]
I have been trying to do QC for nanopore direct RNA sequencing sample using the script bam_alignment_qc.py. However, when I launch, it seems to crash with keyerror message (see below).
The command:
`bam_alignment_qc.py -f ../../../refs/gencode.v32.pc_transcripts.fa -q 5 -p bam_alignment_qc.pk sample.tran.sort.bam`
```
Gathering read and error statistics from file: sample.tran.sort.bam
  0%|                                                                                                              | 0/1195607 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/lynn/miniconda2/envs/nanopore/bin/bam_alignment_qc.py", line 281, in <module>
    args.bam, references, region=args.c, context_sizes=context_sizes, min_aqual=args.q, verbose=verbose)
  File "/home/lynn/miniconda2/envs/nanopore/lib/python3.7/site-packages/wub/bam/stats.py", line 398, in error_and_read_stats
    _update_read_stats(r, read_stats, min_aqual)
  File "/home/lynn/miniconda2/envs/nanopore/lib/python3.7/site-packages/wub/bam/stats.py", line 104, in _update_read_stats
    res['mqfail_aligned_lengths'].append(r.infer_query_length())
KeyError: 'mqfail_aligned_lengths'
```

**Comment by bsipos** [comment]
Hello! Could you please convert the Us to Ts in your input reads by `runnig seqkit seq --rna2dna` before alignment and try again?
