### ISSUE TITLE
WUB is no longer working...

### ISSUE THREAD

**Issue by unique379r** [nanoporetech/wub#9]
Hi 
I installed WUB from conda but none of the tools are working and throwing me an error as some libraries have been removed from bioconda. is it possible that you could update it?

conda 4.10.0
python 3.7.7
OS centOS 7

```
bam_alignment_qc.py -h
Traceback (most recent call last):
  File "/stornext/snfs5/next-gen/scratch/rupesh/Apps/envs/wub/bin/bam_alignment_qc.py", line 16, in <module>
    from wub.bam import stats as bam_stats
  File "/stornext/snfs5/next-gen/scratch/rupesh/Apps/envs/wub/lib/python3.7/site-packages/wub/bam/stats.py", line 11, in <module>
    from wub.util import seq as seq_util
  File "/stornext/snfs5/next-gen/scratch/rupesh/Apps/envs/wub/lib/python3.7/site-packages/wub/util/seq.py", line 9, in <module>
    from Bio.Alphabet.IUPAC import IUPACUnambiguousDNA, IUPACAmbiguousDNA, IUPACUnambiguousRNA
  File "/stornext/snfs5/next-gen/scratch/rupesh/Apps/envs/wub/lib/python3.7/site-packages/Bio/Alphabet/__init__.py", line 21, in <module>
    "Bio.Alphabet has been removed from Biopython. In many cases, the alphabet can simply be ignored and removed from scripts. In a few cases, you may need to specify the ``molecule_type`` as an annotation on a SeqRecord for your script to work correctly. Please see https://biopython.org/wiki/Alphabet for more information."
ImportError: Bio.Alphabet has been removed from Biopython. In many cases, the alphabet can simply be ignored and removed from scripts. In a few cases, you may need to specify the ``molecule_type`` as an annotation on a SeqRecord for your script to work correctly. Please see https://biopython.org/wiki/Alphabet for more information.
```

**Comment by cjw85** [comment]
As noted in the README, wub is no longer maintained or supported. If you provide details of what functionality you would like to use I can maybe direct you to a suitable resource.

**Comment by unique379r** [comment]
Hi
Thank you for your kind reply. I am at the Baylor college of medicine and we are running PromethION to sequence ONT reads, Basically, I Need QC statistics of reads (pass and fail base calls) and QC of BAMs. Might BAM utilities like **"bam_alignment_qc", "bam_multi_qc",  "bam_alignments_compare" , "bam_count_reads" and "bam_cov"** could be useful for my purpose along with any Raw Reads QC calculators would be awesome addition to my pipeline. 
Thanks once again for offering me your help.
